config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  root "hypotheses#index"

  resource :account, only: %i[show edit update]

  get :about, to: "static#about"

  resources :citations, :publications

  resources :hypotheses do
    resources :explanations, only: %i[new create edit update], controller: "hypothesis_explanations"
  end

  resources :user_scores, only: %i[create]

  get "/citations/:publication_id/:citation_id", to: "citations#show"

  post "/webhooks/github", to: "webhooks#github"

  namespace :admin do
    root to: "reporting#index"
    resources :content_commits
  end

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/citation.rb
class Citation < ApplicationRecord
  include FriendlyFindable
  include FlatFileSerializable
  include GithubSubmittable
  include PgSearch::Model

  KIND_ENUM = {
    article: 0,
    official_document: 1, # Includes patents
    legal_citation: 2, # Court decisions?
    government_statistics: 3,
    non_governmental_statistics: 4,
    quote_from_involved_party: 5,
    research: 10,
    research_with_rct: 11,
    research_review: 12,
    research_meta_analysis: 13,
    research_comment: 14
    # maybe case_study?
  }.freeze

  FETCH_WAYBACK_URL = false # TODO: make this actually work

  belongs_to :publication
  belongs_to :creator, class_name: "User"

  has_many :explanation_quotes
  has_many :explanation_quotes_not_removed, -> { not_removed }, class_name: "ExplanationQuote"
  has_many :explanation_quotes_approved, -> { approved }, class_name: "ExplanationQuote"
  has_many :hypotheses, through: :explanation_quotes_not_removed

  validates_presence_of :url
  validates :slug, presence: true, uniqueness: {scope: [:publication_id]}

  enum kind: KIND_ENUM

  before_validation :set_calculated_attributes
  after_commit :add_to_github_content

  scope :by_creation, -> { reorder(:created_at) }

  pg_search_scope :text_search, against: %i[title slug] # TODO: Create tsvector indexes for performance (issues/92)

  def self.kinds
    KIND_ENUM.keys.map(&:to_s)
  end

  def self.kinds_research
    %w[research_comment research_review research_meta_analysis research research_with_rct].freeze
  end

  def self.kinds_data
    {
      article: {humanized: "article"},
      official_document: {humanized: "official document"},
      legal_citation: {humanized: "legal citation"},
      government_statistics: {humanized: "government statistics"},
      non_governmental_statistics: {humanized: "non governmental statistics"},
      quote_from_involved_party: {humanized: "quote from involved party"},
      research: {humanized: "original research"},
      research_with_rct: {humanized: "research with randomized controlled trial"},
      research_review: {humanized: "research review"},
      research_meta_analysis: {humanized: "research meta analysis"},
      research_comment: {humanized: "published research comment"}
    }.freeze
  end

  # Used in flat file import and in controller, so define here
  def self.permitted_attrs
    %i[title authors_str kind url url_is_direct_link_to_full_text published_date_str doi
      url_is_not_publisher publication_title peer_reviewed randomized_controlled_trial]
  end

  def self.kind_humanized(kind)
    kinds_data.dig(kind&.to_sym, :humanized)
  end

  def self.friendly_find_kind(str)
    return nil unless str.present?
    str = str.to_s.strip
    return str.tr(" ", "_") if kinds.include?(str.tr(" ", "_"))
    KIND_ENUM.keys.find do |k, v|
      kinds_data.dig(k, :humanized) == str
    end&.to_s
  end

  def self.find_by_slug_or_path_slug(str)
    return none unless str.present?
    slug = Slugifyer.slugify(str.gsub(/\.yml\z/i, "")) # remove .yml extension, just in case
    where(path_slug: slug).by_creation.first || # exact path_slug matching
      where("path_slug ILIKE ?", "#{slug.truncate(240, omission: "")}%").by_creation.first || # filename truncation
      where(slug: slug).by_creation.first
  end

  def self.friendly_find_slug(str)
    matched = find_by_slug_or_path_slug(str)
    return matched if matched.present?
    # Only try the URL matching if it looks like a URL
    if UrlCleaner.looks_like_url?(str)
      matched = where(url: UrlCleaner.without_utm(str)).first
      return matched if matched.present?
      matched = where("lower(citations.url) ILIKE ?", str.to_s.downcase.strip).first
      # If the beginning of the URL is missing (eg no http) try to make that work
      matched ||= where("lower(citations.url) ILIKE ?", "%#{str.to_s.downcase.strip}").first
      # TODO: remove https://www if still no match, as more fallback
      return matched if matched.present?
    end
    # Try short slug finding
    short_slug = Slugifyer.filename_slugify(str)
    where("slug ILIKE ?", "#{short_slug}%").by_creation.first ||
      where("slug ILIKE ?", "%#{short_slug}%").by_creation.first
  end

  def self.find_or_create_by_params(attrs)
    existing = friendly_find(attrs[:url]) if (attrs || {}).dig(:url).present?
    return create(attrs) if existing.blank?
    existing
  end

  def to_param
    path_slug
  end

  def url_is_publisher?
    !url_is_not_publisher
  end

  def wikipedia?
    publication&.wikipedia?
  end

  def authors_str
    (authors || []).join("; ")
  end

  def publication_title
    publication&.title || @publication_title
  end

  def display_title
    [publication_title, title].uniq.join(": ")
  end

  def authors_str=(val)
    self.authors = val.split(/\n|;/).map(&:strip).reject(&:blank?)
  end

  def publication_title=(val)
    @publication_title = val
    self.publication = Publication.friendly_find(val)
  end

  def published_date_str
    published_at&.to_date&.to_s
  end

  # We're rounding to date - if/when there is a need for additional specificity, handle that previously was just date
  def published_date_str=(val)
    self.published_at = TimeParser.parse(val)&.beginning_of_day
  end

  def peer_reviewed?
    closed_access_peer_reviewed? || open_access_peer_reviewed?
  end

  def kind_data
    kind.present? && self.class.kinds_data.dig(kind.to_sym) || {}
  end

  def kind_humanized
    self.class.kind_humanized(kind)
  end

  def kind_humanized_short
    kind_humanized&.gsub(/\([^)]*\)/, "")
  end

  def kind_selectable?
    true # Should be false if the URL is wikipedia, probably some other publishers too
  end

  # Required for FlatFileSerializable
  def file_pathnames
    ["citations", publication&.slug, "#{slug}.yml"].compact
  end

  # Required for FlatFileSerializable
  def flat_file_serialized
    CitationSerializer.new(self, root: false).as_json
  end

  def title_url?
    url.match?(title)
  end

  def quotes
    explanation_quotes_not_removed.ref_ordered.pluck(:text).uniq
  end

  def quotes_approved
    explanation_quotes_approved.ref_ordered.pluck(:text).uniq
  end

  def skip_author_field?
    wikipedia?
  end

  def skip_published_at_field?
    wikipedia?
  end

  def skip_url_is_direct_link_to_full_text_field?
    wikipedia?
  end

  def set_calculated_attributes
    self.url = UrlCleaner.with_http(UrlCleaner.without_utm(url))
    self.creator_id ||= explanation_quotes.first&.creator_id
    self.publication ||= Publication.find_or_create_by_params(title: @publication_title, url: url, url_is_not_publisher: url_is_not_publisher)
    self.title = UrlCleaner.without_base_domain(url) unless title.present?
    self.slug = Slugifyer.filename_slugify(title)
    self.path_slug = [publication&.slug, slug].compact.join("-")
    self.kind ||= "article" # default to article for now
    self.authors ||= []
    self.url_is_direct_link_to_full_text = true if wikipedia?
    if FETCH_WAYBACK_URL && url_is_direct_link_to_full_text
      self.wayback_machine_url ||= WaybackMachineIntegration.fetch_current_url(url)
    end
  end
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  before_action :redirect_to_signup_unless_user_present!, except: %i[index show]
  before_action :set_permitted_format

  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 500
    @citations = Citation.approved.reorder(created_at: :desc).includes(:publication)
      .page(page).per(per_page)
  end

  def show
    slug = [params[:publication_id], params[:id]].reject(&:blank?).join("-")
    @citation = Citation.friendly_find!(slug)
    @hypotheses = @citation.hypotheses.reorder(created_at: :desc)
    @page_title = @citation.display_title
  end

  private

  # To make it possible to use the file path from a citation directly
  def set_permitted_format
    request.format = "html" unless request.format == "json"
  end
end

app/views/citations/_display.html.haml
- render_waiting_for_approval ||= false
- explanation_quote_id ||= nil

.col-md-6
  - if render_waiting_for_approval && citation.waiting_on_github?
    .alert.alert-info
      - if citation.pull_request_number.present?
        %h4
          Citation waiting on approval,
          = link_to "PR#{citation.pull_request_number}", citation.pull_request_url
      - else
        Waiting for pull request to be created, page will reload.
        -# if citation hasn't been updated recently, skip this (something broke?)
        - if @citation.updated_at > Time.current - 2.minutes
          :javascript
            window.setTimeout(() => {location.reload();}, 1000);

  %table.table-list
    %tbody
      %tr
        %td Title
        %td
          = citation.title
          - unless controller_name == "citations" && action_name == "show"
            = link_to internal_link_text, citation_path(citation.to_param), class: "internal-link"
      %tr
        %td URL
        %td
          - if citation.url.present?
            = link_to citation.url, citation.url
      %tr
        %td GitHub
        %td
          - if citation.approved?
            = link_to citation.file_path.truncate(75), citation.github_html_url, title: citation.file_path
            - if citation.pull_request_number.present?
              %em.small.less-strong.mt-2.d-block
                Approved by
                = link_to "PR##{citation.pull_request_number}", citation.pull_request_url
                - if citation.approved_at.present?
                  %span.convertTime.withPreposition
                    = l citation.approved_at, format: :convert_time
          - else
            %em.less-strong not approved
      - if display_dev_info?
        %tr.only-dev-visible
          %td ID
          %td= citation.id
        - if explanation_quote_id.present?
          %tr.only-dev-visible
            %td
              %small Explanation Quote ID
            %td= explanation_quote_id
      %tr
        %td URL direct link?
        %td= display_true_or_false(citation.url_is_direct_link_to_full_text)
      %tr
        %td Kind
        %td= citation.kind_humanized
      %tr
        %td Peer reviewed?
        %td= display_true_or_false(citation.peer_reviewed)
      %tr
        %td Publication
        %td
          - if citation.publication.present?
            = link_to citation.publication.title, publication_path(citation.publication)
      %tr
        %td Published date
        %td
          -# See note about time specificity in citation - it's why we're doing date, not convertTime
          = citation.published_date_str
      %tr
        %td Authors
        %td
          - if citation.authors.present?
            %ul
              - citation.authors.each do |author|
                %li
                  = author
      %tr
        %td Hypotheses
        %td= citation.hypotheses.count
      %tr
        %td Quotes
        %td
          %ul.small
            - citation.quotes.each do |text|
              %li= text

app/views/citations/_new_fields.html.haml
.form-group
  = form.label :url, "URL"
  = form.text_field :url, required: true, class: "form-control"
.form-group
  = form.label :assignable_kind, "Source kind"
  = form.select :assignable_kind, Citation.assignable_kinds.map { |k| [k.humanize.to_s, k] }, {}, { class: "form-control" }
.form-group
  .form-check
    %label.form-check-label
      = form.check_box :url_is_direct_link_to_full_text, class: "form-check-input"
      URL is a direct link to the full text of the article
  -# Once we have a lot of publications, we may want to show/hide this based on the publication.
  -# For now, just assigning meta_publication to publications is easier to deal with
  -# %label.form-check-label.small
  -#   = form.check_box :url_is_not_publisher, class: "form-check-input"
  -#   URL is not the publisher (e.g. jstor)
.form-group
  = form.label :title do
    -# TODO: Make this update and change based on the assignable_kind
    %span#citationKind
      Article
    title
  = form.text_field :title, placeholder: "optional", class: "form-control"
.form-group
  = form.label :authors_str do
    Authors
    %small.less-strong new line delineated
  = form.text_area :authors_str, placeholder: "optional", class: "form-control"

app/views/citations/_table.html.haml
- citations ||= @citations

.full-screen-table
  %table.table.table-striped.table-sm.table-bordered
    %thead
      - if display_dev_info?
        %th.only-dev-visible.small
          ID
      %th
        Title
      %th
        Created
      %th
        Kind
      %td
        Publication
      %td
        %small Hypothesis count
    %tbody
      - citations.each do |citation|
        %tr
          - if display_dev_info?
            %td.only-dev-visible.small
              = citation.id
          %td
            = citation.title
            = link_to internal_link_text, citation_path(citation.to_param), class: "internal-link"
          %td
            %span.convertTime
              = l citation.created_at, format: :convert_time
          %td
            = citation.kind_humanized_short
          %td
            = citation.publication&.title
          %td
            %small= citation.hypotheses.count

app/views/citations/index.html.haml
%h1 Citations
%p.text-right
  = link_to "add citation", new_citation_path

%p
  %strong
    = number_with_delimiter(@citations.total_count)
  matching citations

.paginate-wrapper
  = paginate @citations

= render partial: "/citations/table", locals: { citations: @citations }

app/views/citations/show.html.haml
%h1.mt-big
  Citation

.row.mt-4
  = render partial: "/citations/display", locals: { citation: @citation, render_waiting_for_approval: true }

%h2.mt-4.mb-1 Hypotheses

= render partial: "/hypotheses/table", locals: { hypotheses: @hypotheses }