config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  root "hypotheses#index"

  resource :account, only: %i[show edit update]

  get :about, to: "static#about"

  resources :citations, :publications

  resources :hypotheses do
    resources :explanations, only: %i[new create edit update], controller: "hypothesis_explanations"
  end

  resources :user_scores, only: %i[create]

  get "/citations/:publication_id/:citation_id", to: "citations#show"

  post "/webhooks/github", to: "webhooks#github"

  namespace :admin do
    root to: "reporting#index"
    resources :content_commits
  end

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/controllers/hypotheses_controller.rb
class HypothesesController < ApplicationController
  before_action :redirect_to_signup_unless_user_present!, except: %i[index show]
  before_action :process_user_score
  before_action :find_hypothesis, except: %i[index new create]
  before_action :ensure_user_can_edit!, only: %i[edit update]
  before_action :set_permitted_format

  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 500
    @hypotheses = matching_hypotheses.newness_ordered.page(page).per(per_page)
    @page_title = "Convus"
  end

  def show
    @page_title = @hypothesis.title
    if params[:explanation_id].present?
      explanation = @hypothesis.explanations.find_by_ref_number(params[:explanation_id])
      if explanation.blank?
        flash[:error] = "Unable to find that explanation"
      elsif explanation.approved?
        flash[:success] = "Explanation has been approved and is included on this page"
      else
        @unapproved_explanations = @hypothesis.explanations.where(ref_number: params[:explanation_id])
      end
    end
    @explanations = @hypothesis.explanations.approved
    @hypotheses_relations = @hypothesis.relations.shown(current_user)
    @unapproved_explanations ||= @hypothesis.explanations.unapproved.shown(current_user)
      .order(updated_at: :desc)
  end

  def new
    @hypothesis ||= Hypothesis.new
    if params[:related_hypothesis_id].present?
      @hypothesis_related = Hypothesis.friendly_find(params[:related_hypothesis_id])
      @hypothesis_related_kind = params[:related_kind] if HypothesisRelation.kinds.include?(params[:related_kind])
    end
  end

  def create
    @hypothesis = Hypothesis.new(permitted_params)
    @hypothesis.creator_id = current_user.id
    if @hypothesis.save
      update_hypothesis_relation(params[:hypothesis_relation_kind], params[:hypothesis_relation_id])
      flash[:success] = "Hypothesis created!"
      redirect_to new_hypothesis_explanation_path(hypothesis_id: @hypothesis.ref_id)
    else
      render :new
    end
  end

  helper_method :matching_hypotheses

  private

  # To make it possible to use the file path from a hypothesis directly
  def set_permitted_format
    request.format = "html" unless request.format == "json"
  end

  def find_hypothesis
    @hypothesis = Hypothesis.friendly_find!(params[:id])
    @citations = @hypothesis.citations
  end

  def process_user_score
    return true if session[:after_sign_in_score].blank? || current_user.blank?
    new_score_data = session.delete(:after_sign_in_score)
    hypothesis_id, score, kind = new_score_data.split(",")
    return true if [hypothesis_id, score, kind].compact.count < 3
    new_score = current_user.user_scores.new(hypothesis_id: hypothesis_id, kind: kind, score: score)
    new_score.set_calculated_attributes
    most_recent_score = current_user.user_scores.current.where(hypothesis_id: hypothesis_id, kind: kind).last
    return true if most_recent_score&.score == new_score.score
    new_score.save
  end

  def ensure_user_can_edit!
    return true if @hypothesis.editable_by?(current_user)
    flash[:error] = if @hypothesis.not_submitted_to_github?
      "You can't edit that hypothesis because you didn't create it"
    else
      "You can't edit hypotheses that have been submitted"
    end
    redirect_to hypothesis_path(@hypothesis)
    nil
  end

  def matching_hypotheses
    return @matching_hypotheses if defined?(@matching_hypotheses)
    hypotheses = ParamsNormalizer.boolean(params[:search_unapproved]) ? Hypothesis.unapproved : Hypothesis.approved

    if params[:search_array].present?
      matches = Tag.matching_tag_ids_and_non_tags(params[:search_array])
      @search_tags = Tag.where(id: matches[:tag_ids])
      hypotheses = hypotheses.with_tag_ids(@search_tags.pluck(:id)) if @search_tags.any?
      hypotheses = hypotheses.text_search(matches[:non_tags]) if matches[:non_tags].any?
      @search_items = @search_tags.pluck(:title) + matches[:non_tags]
    else
      @search_items = []
    end

    @matching_hypotheses = hypotheses
  end

  def permitted_params
    # Permit tags_string as a string or an array
    params.require(:hypothesis).permit(:title, :add_to_github, :tags_string, tags_string: [])
  end

  # Duplicated in HypothesesExplanationController
  def update_hypothesis_relation(kind, id)
    other_hypothesis = Hypothesis.find_by_id(id)
    return nil unless other_hypothesis.present? && HypothesisRelation.kinds.include?(kind)
    HypothesisRelation.find_or_create_for(kind: kind,
      hypotheses: [@hypothesis, other_hypothesis],
      creator: current_user)
    @hypothesis.reload # Make sure the hypothesis comes along too
  end
end

app/views/hypotheses/_hypothesis_citation_challenge_list.html.haml
- challenges = hypothesis_citation.challenges.approved
- has_challenge = challenges.any?
%li{class: (has_challenge ? "citation-challenged" : "")}
  - if has_challenge
    %span.challenge-connecting-line
  = render partial: "/hypotheses/show_hypothesis_citation", locals: {hypothesis_citation: hypothesis_citation, rendering_list: true, rendering_challenge: has_challenge}
  - if has_challenge
    %ul
      - challenges.each do |challenge|
        = render partial: "/hypotheses/hypothesis_citation_challenge_list", locals: {hypothesis_citation: challenge}

app/views/hypotheses/_list.html.haml
- hypotheses ||= @hypotheses
- skip_citations ||= false
- skip_citation_id ||= nil
- search_items ||= @search_items || []

.hypotheses-list
  %ul
    - hypotheses.each do |hypothesis|
      %li
        .d-block
          = hypothesis.title
          = link_to internal_link_text, hypothesis_path(hypothesis.to_param), class: "internal-link"
        .hypothesis-info
          -# Time hidden for now because it isn't that important
          -# %small.less-strong.convertTime.d-inline-block
          -#   = l hypothesis.created_at, format: :convert_time
          -# Score hidden for now, because it's inaccurate
          -# .score-bubble.small{ class: hypothesis_score_class(hypothesis.score) }
          -#   = hypothesis.score
          - hypothesis.tags.each do |tag|
            = link_to tag.title, hypotheses_path(sortable_search_params.merge(search_array: (search_items + [tag.title]))), class: "tag-bubble small"

app/views/hypotheses/_relation_field.html.haml
- relation_kind ||= nil
- related_id ||= nil
- initially_toggled ||= related_id.present?

.max-width-text-container.col.collapse#hypothesisRelationField{class: (initially_toggled ? "show" : "")}
  - relations_kinds = [["conflicting", "hypothesis_conflict"], ["supporting", "hypothesis_support"]]
  = label_tag :hypothesis_relation_id do
    Related
    = select_tag :hypothesis_relation_kind, options_for_select(relations_kinds, relation_kind), class: "ml-1 mr-1"
    hypothesis
  .form-group.fancy-select.unfancy
    - relatable_hypotheses = Hypothesis.shown(current_user).map { |h| [h.title_with_tags, h.id] }
    = select_tag :hypothesis_relation_id, options_for_select(relatable_hypotheses, related_id), {class: "form-control", required: false, multiple: false, prompt: "Select hypothesis"}

app/views/hypotheses/_show_citation_argument_quotes.html.haml
-# Must pass in hypothesis citation
- skip_challenge ||= false
- citation ||= argument_quotes.first.citation

.col-xl-6.mt-2.mb-2
  .hypothesis-quotes-block
    - argument_quotes.each do |argument_quote|
      %blockquote
        = argument_quote.text

  %table.table-list.mb-0
    %tbody
      %tr
        %td Title
        %td
          = citation.title
      %tr
        %td URL
        %td
          = link_to citation.url, citation.url
      %tr
        %td Publication
        %td
          - if citation.publication.present?
            = link_to citation.publication.title, publication_path(citation.publication)
      - unless citation.skip_published_at_field?
        %tr
          %td Published date
          %td= citation.published_date_str
      - unless citation.skip_author_field?
        %tr
          %td Author
          %td
            - if citation.authors.count < 2
              = citation.authors.first
            - else
              %ul
                - citation.authors.each do |author|
                  %li
                    = author
      %tr
        %td Kind
        %td= citation.kind_humanized
      %tr
        %td DOI
        %td= citation.doi
      %tr
        %td Convus GitHub
        %td
          = link_to citation.file_path.truncate(75), citation.github_html_url, title: citation.file_path
          - if citation.pull_request_number.present?
            %em.small.less-strong.mt-2.d-block
              Approved by
              = link_to "PR##{citation.pull_request_number}", citation.pull_request_url
              - if citation.approved_at.present?
                %span.convertTime.withPreposition
                  = l citation.approved_at, format: :convert_time
          - else
            %em.less-strong not approved
      - if display_dev_info?
        %tr.only-dev-visible
          %td Citation show
          %td
            = link_to citation_path(citation).to_s.truncate(75), citation_path(citation)

app/views/hypotheses/_show_citation_explanation_quotes.html.haml
-# Must pass in hypothesis citation
- skip_challenge ||= false
- citation ||= explanation_quotes.first.citation

.col-xl-6.mt-2.mb-2
  .hypothesis-quotes-block
    - explanation_quotes.each do |explanation_quote|
      %blockquote
        = explanation_quote.text
  .full-screen-table
    %table.table-list.mb-0
      %tbody
        %tr
          %td Title
          %td
            = citation.title
        %tr
          %td URL
          %td
            = link_to citation.url, citation.url
        %tr
          %td Publication
          %td
            - if citation.publication.present?
              = link_to citation.publication.title, publication_path(citation.publication)
        - unless citation.skip_published_at_field?
          %tr
            %td Published date
            %td= citation.published_date_str
        - unless citation.skip_author_field?
          %tr
            %td Author
            %td
              - if citation.authors.count < 2
                = citation.authors.first
              - else
                %ul.small.mt-0.mb-0
                  - citation.authors.each do |author|
                    %li
                      = author
        %tr
          %td Kind
          %td= citation.kind_humanized
        %tr
          %td DOI
          %td= citation.doi
        %tr
          %td Convus GitHub
          %td
            = link_to citation.file_path.truncate(75), citation.github_html_url, title: citation.file_path
            - if citation.pull_request_number.present?
              %em.small.less-strong.mt-2.d-block
                Approved by
                = link_to "PR##{citation.pull_request_number}", citation.pull_request_url
                - if citation.approved_at.present?
                  %span.convertTime.withPreposition
                    = l citation.approved_at, format: :convert_time
            - else
              %em.less-strong not approved
        - if display_dev_info?
          %tr.only-dev-visible
            %td Citation show
            %td
              = link_to citation_path(citation).to_s.truncate(75), citation_path(citation)

app/views/hypotheses/_show_title.html.haml
- hypothesis ||= @hypothesis
- render_show_link ||= false

.max-width-text-container.col
  %p.mt-4
    %span{ style: "font-size: 125%;" }
      = hypothesis.title
      - if render_show_link
        = link_to internal_link_text, hypothesis_path(hypothesis.to_param), class: "internal-link small", data: { confirm: "Are you sure? You will lose unsaved changes!" }
  %p.mt-4.mb-0
    -# Time hidden for now because it isn't that important
    -# %small.less-strong.convertTime.d-inline-block
    -#   = l hypothesis.created_at, format: :convert_time
    -# Score hidden for now, because it's inaccurate
    -# .score-bubble.small{ class: hypothesis_score_class(hypothesis.score) }
    -#   = hypothesis.score
    - hypothesis.tags.each do |tag|
      = link_to tag.title, hypotheses_path(search_array: tag.title), class: "tag-bubble small"

app/views/hypotheses/_table.html.haml
- hypotheses ||= @hypotheses
- skip_citations ||= false
- skip_citation_id ||= nil
- link_to_edit ||= false

.full-screen-table
  %table.table.table-striped.table-sm.table-bordered
    %thead
      - if display_dev_info?
        %th.only-dev-visible.small.d-none.d-md-table-cell
          ID
        %th.only-dev-visible.small.d-none.d-md-table-cell
          Ref ID
      %th.d-none.d-md-table-cell
        Hypothesis
      %th.d-none.d-md-table-cell
        Citations
      %th.d-none.d-md-table-cell
        Created
    %tbody
      - search_items = @search_items || []
      - hypotheses.each do |hypothesis|
        %tr
          - if display_dev_info?
            %td.only-dev-visible.small
              = hypothesis.id
            %td.only-dev-visible.small
              = hypothesis.ref_id
          %td
            = hypothesis.title

            = link_to internal_link_text, hypothesis_path(hypothesis.to_param), class: "internal-link"
            - hypothesis.tags.each do |tag|
              = link_to tag.title, hypotheses_path(sortable_search_params.merge(search_array: (search_items + [tag.title]))), class: "tag-bubble small"

          %td.d-none.d-md-table-cell
            %ul
              - hypothesis.citations.each do |citation|
                - next if citation.id == skip_citation_id
                %li.small
                  - if citation.publication.present? && !citation.publication.title_url?
                    #{citation.publication.title}:
                  %em
                    = citation.title.truncate(75)
                  %small.less-strong
                    #{citation.quotes.count}
                    = "quote".pluralize(citation.quotes.count)

          %td.d-none.d-md-table-cell
            %small.convertTime
              = l hypothesis.created_at, format: :convert_time

app/views/hypotheses/index.html.haml
.max-width-text-container-centered
  - unless sortable_search_params?
    %h1.landing-title Working toward truth

  .row.mt-4
    .col-sm-4.mb-2.mt-2
      %strong
        = number_with_delimiter(@hypotheses.total_count)
      - if sortable_search_params?
        matching
      = "hypothesis".pluralize(@hypotheses.total_count)
    .col-sm-8.hypotheses-search.mb-2
      = form_tag hypotheses_path, method: "GET", class: "form-inline justify-content-end" do
        .form-group.hypotheses-search-select-group.fancy-select.unfancy.create-options-search
          - search_options = (@search_items + tag_titles).uniq # include non-tag search items in search box
          = select_tag :search_array, options_for_select(search_options, @search_items), class: "form-control ", prompt: "Matching topics", multiple: true
        = submit_tag "Search", class: "btn btn-outline-primary hypotheses-search-btn"

  .paginate-wrapper
    = paginate @hypotheses
  .mt-4

- if ParamsNormalizer.boolean(params[:render_table])
  = render partial: "/hypotheses/table", locals: { hypotheses: @hypotheses }
- else
  = render partial: "/hypotheses/list", locals: { hypotheses: @hypotheses }

app/views/hypotheses/new.html.haml
- relation_initially_toggled = @hypothesis_related.present?
.small-page-header
  %h1.mb-3
    New Hypothesis
    - unless relation_initially_toggled
      %small
        %a.gray-link.small{href: "#hypothesisRelationField", tabindex: -1, "role" => "button", "aria-expanded" => "false", "data-toggle" => "collapse", "data-querykey" => "show_raw", "data-queryvalue" => "true"}
          add hypothesis relationship

= form_for @hypothesis, url: hypotheses_path, method: "POST", html: { class: "form", id: "hypothesisForm" } do |f|
  .row.mb-4
    - if @hypothesis.errors.any?
      .col-md-8.col-xl-6
        = render partial: "/shared/errors", locals: { name: "Hypothesis", obj: @hypothesis }

    = render partial: "/hypotheses/relation_field", locals: {relation_kind: @hypothesis_related_kind, related_id: @hypothesis_related&.id}

    .max-width-text-container.col
      .form-group
        = f.label :title do
          Hypothesis text
          %span.small.less-strong
            must be falsifiable
        = f.text_area :title, required: true, class: "form-control"
  .row
    .col
      .form-group
        = submit_tag "Save", class: "btn btn-primary"
        %em.small.less-strong.ml-2 after saving, you will be able to add an explanation

%hr.mt-big
= render "/shared/content_license"

app/views/hypotheses/show.html.haml
.small-page-header
  %h1
    %span.d-none.d-md-block
      Hypothesis:
.row
  = render partial: "/hypotheses/show_title", locals: {hypothesis: @hypothesis}

  -# Hide scoring! Keep it around as reference for now though
  -# - if @hypothesis.approved?
  -#   -# TODO: this is hacked to make sure it doesn't split into multiple lines. It would be great to handle that better
  -#   .col-xl.mt-4.mb-2{ style: "min-width: 330px;" }
  -#     .text-right.less-strong
  -#       .hypothesis-score
  -#         - quality_score = @hypothesis.user_scores.current.quality.where(user_id: current_user&.id).first
  -#         - if quality_score.present?
  -#           quality
  -#           <div class="current-avg less-strong">(<span>avg</span> #{@hypothesis.user_scores.quality.current_score})</div>:
  -#         - else
  -#           quality:
  -#         - Array(UserScore::MIN_SCORE..UserScore::MAX_SCORE).each do |score|
  -#           - active = quality_score&.score == score
  -#           - if quality_score.present? # Yah, I know, you could still make the form request manually, but who cares that much?
  -#             %span.score-item{class: (active ? "active" : "")}= score
  -#           - else
  -#             = button_to score, user_scores_path, {action: "create", params: {score: score, hypothesis_id: @hypothesis.ref_id, kind: "quality"}, class: "score-item btn btn-link #{active ? 'active' : ''}"}
  -#      .hypothesis-score.mt-2
  -#        - controversy_score = @hypothesis.user_scores.current.controversy.where(user_id: current_user&.id).first
  -#        - if controversy_score.present?
  -#          controversy
  -#          <div class="current-avg less-strong">(<span>avg</span> #{@hypothesis.user_scores.controversy.current_score})</div>:
  -#        - else
  -#          controversy:
  -#        - Array(UserScore::MIN_SCORE..UserScore::MAX_SCORE).each do |score|
  -#          - active = controversy_score&.score == score
  -#          - if controversy_score.present?
  -#            %span.score-item{class: (active ? "active" : "")}= score
  -#          - else
  -#            = button_to score, user_scores_path, {action: "create", params: {score: score, hypothesis_id: @hypothesis.ref_id, kind: "controversy"}, class: "score-item btn btn-link #{active ? 'active' : ''}"}
- if @explanations.any? || @unapproved_explanations
  .explanations-wrapper.row.pb-4
    - @unapproved_explanations.each do |explanation|
      = render partial: "/hypothesis_explanations/show", locals: {explanation: explanation, unapproved_show: true, unapproved_show_linked: params[:explanation_id].present?}

    - @explanations.each do |explanation|
      = render partial: "/hypothesis_explanations/show", locals: {explanation: explanation}

- if @hypotheses_relations.any?
  - relation_col_class = @hypotheses_relations.conflicting.any? && @hypotheses_relations.supporting.any? ? "col-lg-6" : "col-12"
  .row.mt-sm-4
    - if @hypotheses_relations.conflicting.any?
      %div{class: relation_col_class}
        %h5
          Hypotheses that
          %strong conflict
          with this
        %ul
          - @hypotheses_relations.conflicting.each do |hypothesis_relation|
            - other_hypothesis = hypothesis_relation.hypothesis_not(@hypothesis)
            %li
              = other_hypothesis.title
              = link_to internal_link_text, hypothesis_path(other_hypothesis.to_param), class: "internal-link"
              - unless hypothesis_relation.approved?
                %span.less-strong.small.ml-1
                  %em
                    shown because you created it. It is
                    %strong.text-warning not
                    approved.
    - if @hypotheses_relations.supporting.any?
      %div{class: relation_col_class}
        %h5
          %strong Supporting
          Hypotheses
        %ul
          - @hypotheses_relations.supporting.each do |hypothesis_relation|
            - other_hypothesis = hypothesis_relation.hypothesis_not(@hypothesis)
            %li
              = other_hypothesis.title
              = link_to internal_link_text, hypothesis_path(other_hypothesis.to_param), class: "internal-link"
              - unless hypothesis_relation.approved?
                %span.less-strong.small.ml-1
                  %em
                    shown because you created it. It is
                    %strong.text-warning not
                    approved.


- if @hypothesis.approved?
  .row
    .max-width-text-container.col.d-flex.justify-content-between
      = link_to new_hypothesis_explanation_path(hypothesis_id: @hypothesis.ref_id), class: "btn btn-sm btn-outline-secondary mt-4" do
        - if @hypothesis.explanations.shown(current_user).count > 0
          Add
          %span.d-none.d-sm-inline another
          explanation
        - else
          Add explanation
      = link_to "Add conflicting hypothesis", new_hypothesis_path(related_hypothesis_id: @hypothesis.ref_id, related_kind: "hypothesis_conflict"), class: "btn btn-sm btn-outline-danger mt-4 ml-1"

.row.pt-2.mt-5
  - if @explanations.any?
    - @explanations.explanation_quotes.not_removed.ref_ordered.group_by(&:citation_id).each do |_citation_id, explanation_quotes|
      = render partial: "/hypotheses/show_citation_explanation_quotes", locals: {explanation_quotes: explanation_quotes}

.row.mt-big
  .col-md-6
    %table.table-list
      %tbody
        %tr
          %td Hypothesis
          %td= @hypothesis.title
        %tr
          %td Created
          %td
            %span.convertTime.preciseTime
              = l @hypothesis.created_at, format: :convert_time
        %tr
          %td ID
          %td
            = @hypothesis.ref_id
        - if display_dev_info?
          %tr.only-dev-visible.small
            %td ID
            %td
              = @hypothesis.id
          %tr.only-dev-visible
            %td slug
            %td= @hypothesis.to_param
        %tr
          %td GitHub
          %td
            - if @hypothesis.approved?
              = link_to @hypothesis.file_path.truncate(75), @hypothesis.github_html_url, title: @hypothesis.file_path
              - if @hypothesis.pull_request_number.present?
                %em.small.less-strong.d-block.mt-2
                  Approved by
                  = link_to "PR##{@hypothesis.pull_request_number}", @hypothesis.pull_request_url
                  - if @hypothesis.approved_at.present?
                    %span.convertTime.withPreposition
                      = l @hypothesis.approved_at, format: :convert_time