config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  root "hypotheses#index"

  resource :account, only: %i[show edit update]

  get :about, to: "static#about"

  resources :citations, :publications

  resources :hypotheses do
    resources :explanations, only: %i[new create edit update], controller: "hypothesis_explanations"
  end

  resources :user_scores, only: %i[create]

  get "/citations/:publication_id/:citation_id", to: "citations#show"

  post "/webhooks/github", to: "webhooks#github"

  namespace :admin do
    root to: "reporting#index"
    resources :content_commits
  end

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/content_commit.rb
# NOTE: for now, we're only recording commits to the main branch

class ContentCommit < ApplicationRecord
  validates :sha, allow_blank: false, uniqueness: true

  before_validation :set_calculated_attributes

  def message
    github_data.dig("commit", "message")
  end

  def reconciler_update?
    author == "convus-admin-bot" && message.start_with?("Reconciliation:")
  end

  def set_calculated_attributes
    self.sha ||= github_data&.dig("sha")
    self.committed_at ||= TimeParser.parse(github_data_committed_at)
    self.author ||= github_data_author
  end

  def github_data_author
    github_data.dig("author", "login")
  end

  def github_data_committed_at
    github_data&.dig("commit", "committer", "date")
  end
end

app/controllers/admin/content_commits_controller.rb
# frozen_string_literal: true

class Admin::ContentCommitsController < Admin::BaseController
  include SortableTable
  before_action :set_period, only: [:index]

  def index
    page = params[:page] || 1
    @per_page = params[:per_page] || 25
    @render_chart = ParamsNormalizer.boolean(params[:render_chart])
    @time_range_column = set_time_range_column
    @content_commits = matching_content_commits.reorder("#{sort_column} #{sort_direction}")
      .page(page).per(@per_page)
  end

  helper_method :matching_content_commits

  private

  def sortable_columns
    %w[committed_at id created_at updated_at author]
  end

  def set_time_range_column
    if sort_column == "created_at"
      "created_at"
    elsif sort_column == "updated_at"
      "updated_at"
    else # Defaults to committed_at
      "committed_at"
    end
  end

  def matching_content_commits
    content_commits = ContentCommit

    content_commits.where(@time_range_column => @time_range)
  end
end

app/views/admin/content_commits/index.html.haml
.admin-header
  .row
    .col-sm-4
      %h1
        Content Commits
    .col-sm-8
      %ul
        %li.nav-item
          = link_to "render chart", admin_content_commits_path(sortable_search_params.merge(render_chart: !@render_chart)), class: "nav-link #{@render_chart ? 'active' : ''}"


- if @render_chart
  .col-12.mt-2
    = column_chart time_range_counts(collection: matching_content_commits, column: @time_range_column), stacked: true, thousands: ",", defer: true

= render partial: "/shared/period_select"

= render partial: "/shared/pagination", locals: {collection: @content_commits, count: matching_content_commits.count, name: "Content Commit"}

.mt-4.full-screen-table
  %table.table.table-sm.table-bordered.table-striped
    %thead.sortable
      - if display_dev_info?
        %th.only-dev-visible
          %small= sortable "id"
      %th= sortable "committed_at"
      %th
        %small= sortable "created_at"
      %th
        %small= sortable "updated_at"
      %th= sortable "author"
      %th data
    %tbody
      - @content_commits.each do |content_commit|
        %tr
          - if display_dev_info?
            %td
              %small.less-strong
                = content_commit.id
          %td
            - if content_commit.committed_at.present?
              %span.convertTime
                = l content_commit.committed_at, format: :convert_time
          %td
            %small.convertTime
              = l content_commit.created_at, format: :convert_time
          %td
            %small.convertTime
              = l content_commit.updated_at, format: :convert_time
          %td
            = content_commit.author
          %td
            .overflow{ style: "max-width: 50%; height: 300px; overflow: scroll;" }
              = pretty_print_json(content_commit.github_data)