config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    get "users/sign_out" => "devise/sessions#destroy"
  end

  root "hypotheses#index"

  resource :account, only: %i[show edit update]

  get :about, to: "static#about"

  resources :citations, :publications

  resources :hypotheses do
    resources :explanations, only: %i[new create edit update], controller: "hypothesis_explanations"
  end

  resources :user_scores, only: %i[create]

  get "/citations/:publication_id/:citation_id", to: "citations#show"

  post "/webhooks/github", to: "webhooks#github"

  namespace :admin do
    root to: "reporting#index"
    resources :content_commits
  end

  authenticate :user, lambda { |u| u.developer? } do
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/controllers/hypothesis_explanations_controller.rb
class HypothesisExplanationsController < ApplicationController
  before_action :redirect_to_signup_unless_user_present!
  before_action :find_hypothesis_explanation
  before_action :ensure_user_can_edit!, only: %i[edit update]
  before_action :set_permitted_format

  def edit
    @page_title = "Edit Explanation: #{@hypothesis.title}"
  end

  def new
    @page_title = "Add Explanation: #{@hypothesis.title}"
    if @explanation.blank? # Just in case we're rendering again
      @explanation = @hypothesis.explanations.build
    end
  end

  def create
    @explanation = @hypothesis.explanations.build(permitted_params)
    @explanation.creator_id = current_user.id
    if @explanation.save
      update_hypothesis_if_permitted
      @explanation.update_body_html
      flash[:success] = "Explanation added!"
      redirect_to edit_hypothesis_explanation_path(id: @explanation.id, hypothesis_id: @hypothesis.ref_id)
    else
      render :new
    end
  end

  def update
    previous_explanation_quote_ids = @explanation.explanation_quotes.pluck(:id).map(&:to_s)
    update_successful = @explanation.update(permitted_params)
    if update_successful
      update_hypothesis_if_permitted
      @explanation.remove_empty_quotes!
      # Remove explanation_quotes that weren't included in the params (they were removed on the frontend)
      updated_quote_ids = permitted_params[:explanation_quotes_attributes]&.keys || []
      @explanation.explanation_quotes.where(id: previous_explanation_quote_ids - updated_quote_ids).destroy_all
      @explanation.update_body_html
      @explanation.reload # Because maybe things were deleted!
      update_citations_if_permitted
      # Manually trigger to ensure it happens after explanation is updated
      if ParamsNormalizer.boolean(params.dig(:explanation, :add_to_github)) && @explanation.validate_can_add_to_github?
        @explanation.update(add_to_github: true)
        flash[:success] = "Explanation submitted for review"
        redirect_to hypothesis_path(@hypothesis.ref_id, explanation_id: @explanation.ref_number)
      else
        if @explanation.errors.full_messages.any? # Happens when fail to submit to github
          flash[:error] = @explanation.errors.full_messages.join(", ")
        else
          flash[:success] = "Explanation saved"
        end
        target_url_params = {hypothesis_id: @hypothesis.ref_id, id: @explanation.id}
        # Don't include initially_toggled paramets unless it's passed because it's ugly
        target_url_params[:initially_toggled] = true if ParamsNormalizer.boolean(params[:initially_toggled])
        redirect_to edit_hypothesis_explanation_path(target_url_params)
      end
    else
      render :edit
    end
  end

  private

  # To make it possible to use the file path from a explanation directly
  def set_permitted_format
    request.format = "html" unless request.format == "json"
  end

  def find_hypothesis_explanation
    @hypothesis = Hypothesis.friendly_find!(params[:hypothesis_id])
    @explanation = Explanation.find_by_id(params[:id])
  end

  def ensure_user_can_edit!
    return true if @explanation.editable_by?(current_user)
    flash[:error] = flash[:error] = if @explanation.not_submitted_to_github?
                      "You can't edit that explanation because you didn't create it"
                    else
                      "You can't edit explanations that have been submitted"
                    end
    redirect_to hypothesis_path(@hypothesis)
    nil
  end

  def update_hypothesis_if_permitted
    return unless @hypothesis.editable_by?(current_user) &&
      (params[:hypothesis_title].present? || params[:hypothesis_tag_string].present?)

    @hypothesis.title = params[:hypothesis_title] if params[:hypothesis_title].present?
    @hypothesis.tags_string = params[:hypothesis_tags_string] if params[:hypothesis_tags_string]
    @hypothesis.save
    hypothesis_relation = update_hypothesis_relation(params[:hypothesis_relation_kind], params[:hypothesis_relation_id])
    # Remove any hypothesis relations that are no longer relevant
    @hypothesis.reload.relations.unapproved.where.not(id: hypothesis_relation&.id)
      .where(hypothesis_later_id: @hypothesis.id)
      .destroy_all
  end

  def permitted_params
    params.require(:explanation).permit(:text,
      explanation_quotes_attributes: [:url, :text, :ref_number, :id, :removed])
  end

  def update_citations_if_permitted
    (permitted_citations_params || []).each do |_id, attrs|
      explanation_quote = @explanation.explanation_quotes.find_by_id(attrs[:explanation_quote_id])
      citation = explanation_quote&.citation
      citation.update!(attrs.except(:explanation_quote_id)) if citation&.editable_by?(current_user)
    end
  end

  # Get each set of permitted citation attributes. We're updating them individually
  def permitted_citations_params
    params.require(:explanation)
      .permit(citations_attributes: Citation.permitted_attrs + [:explanation_quote_id])
      .dig(:citations_attributes)
  end

  # Duplicated in HypothesesController
  def update_hypothesis_relation(kind, id)
    other_hypothesis = Hypothesis.find_by_id(id)
    return nil unless other_hypothesis.present? && HypothesisRelation.kinds.include?(kind)
    HypothesisRelation.find_or_create_for(kind: kind,
      hypotheses: [@hypothesis, other_hypothesis],
      creator: current_user)
  end
end

app/views/hypothesis_explanations/_citation_fields.html.haml
- render_full_fields ||= false
-# initially_toggled is only really for development, when working on the view
- initially_toggled ||= false
- initially_toggled = false unless render_full_fields
- citation ||= f.object
- explanation_quotes ||= []

= f.hidden_field :id # necessary to do manually, or else it isn't included for new objects
= f.hidden_field :explanation_quote_id, value: explanation_quotes.first&.id # Hidden because
.col-md-6.mb-4.mt-2.collapse.citationFields.show
  .citation-quotes-block
    - explanation_quotes.each do |explanation_quote|
      %blockquote.mt-1{id: "citationExplanationQuote-#{explanation_quote.id}"}
        = explanation_quote.text
  - if citation.editable_by?(current_user)
    .citation-editable-fields
      .form-group.mt-0
        = f.label :title, "Article title"
        = f.text_field :title, placeholder: "optional", class: "form-control"

      - if citation.kind_selectable?
        .form-group
          = f.label :kind, "Citation kind"
          - citation_kind_opts = options_for_select(Citation.kinds.map { |k| [Citation.kind_humanized(k)&.titleize, k] }, citation.kind)
          = f.select :kind, citation_kind_opts, {}, { class: "form-control citationKindSelect" }

      .form-group.mt-0.collapse.kindResearchField
        .form-check
          %label.form-check-label
            = f.check_box :peer_reviewed, class: "form-check-input"
            Citation was peer reviewed before publication

      - unless citation.skip_url_is_direct_link_to_full_text_field?
        .form-group.mt-0
          .form-check
            %label.form-check-label
              = f.check_box :url_is_direct_link_to_full_text, class: "form-check-input"
              URL is a direct link to the full text of the citation

      -#.form-group.mt-0
      -#  .form-check
      -#    %label.form-check-label
      -#      = f.check_box :randomized_controlled_trial, class: "form-check-input"
      -#      Citation is about a randomized controlled trial
      -# Once we have a lot of publications, we may want to show/hide this based on the publication.
      -# For now, just assigning meta_publication to publications is easier to deal with
      -# %label.form-check-label.small
      -#   = f.check_box :url_is_not_publisher, class: "form-check-input"
      -#   URL is not the publisher (e.g. jstor)
      -# Only show the publication title field if it hasn't been previously set
      - if citation&.publication&.title_url?
        .form-group
          = f.label :publication_title
          = f.text_field :publication_title, placeholder: "optional", class: "form-control"

      - unless citation.skip_author_field?
        .form-group
          = f.label :authors_str do
            Authors
            %small.less-strong new line delineated
          = f.text_area :authors_str, value: citation.authors&.join("\n"), placeholder: "optional", class: "form-control"
      - unless citation.skip_published_at_field?
        .form-group
          = f.label :published_date_str do
            Published date
            %small.less-strong YYYY-MM-DD
          = f.text_field :published_date_str, placeholder: "optional", class: "form-control"
      .form-group.mt-0.collapse.kindResearchField
        = f.label :doi do
          DOI
          = link_to "digital object identifier", "https://en.wikipedia.org/wiki/Digital_object_identifier", target: "_blank", class: "small less-strong"
        = f.text_field :doi, placeholder: "optional", class: "form-control"
  - else
    %table.table-list.mb-0
      %tbody
        %tr
          %td{colspan: 2}
            You can't edit this citation, it's already been approved. Suggest changes to
            -# github_html_url should always be present here... but if it's broken, and the url is blank, clicking the link just reloads the page which is super confusing and unhelpful. So at least send the user to a page to see the citation
            - suggest_url = citation.github_html_url || citation_path(citation)
            = link_to "the file on GitHub", suggest_url, target: "_blank"

        %tr
          %td Title
          %td
            = citation.title
        %tr
          %td URL
          %td
            = link_to citation.url, citation.url
        %tr
          %td Kind
          %td= citation.kind_humanized
        %tr
          %td Publication
          %td
            - if citation.publication.present?
              = link_to citation.publication.title, publication_path(citation.publication)
              - citation.publication.badges.keys.each do |badge|
                %em.small.less-strong
                  = CitationScorer.badge_humanized(badge)
        - unless citation.skip_published_at_field?
          %tr
            %td Published date
            %td= citation.published_date_str
        - unless citation.skip_author_field?
          %tr
            %td Author
            %td
              - if citation.authors.count < 2
                = citation.authors.first
              - else
                %ul
                  - citation.authors.each do |author|
                    %li
                      = author
        %tr
          %td DOI
          %td= citation.doi

app/views/hypothesis_explanations/_explanation_quote_fields.html.erb
<%#
  NOTE: This is copied in explanation_form.js - which is why this is in erb (closer to the JS template)
  Differences: This always includes the ID input (and never has newQuote class)
%>
<div class="quote-field <%= explanation_quote.removed ? 'removedQuote' : '' %>" id="quoteId-<%= explanation_quote.id %>">
  <%# NOTE: the ID field should only be filled in if the ID exists %>
  <input type="hidden" name="explanation[explanation_quotes_attributes][<%= explanation_quote.id %>][id]" id="explanation_explanation_quotes_attributes_<%= explanation_quote.id %>_id" value="<%= explanation_quote.id %>">
  <input type="hidden" name="explanation[explanation_quotes_attributes][<%= explanation_quote.id %>][ref_number]" id="explanation_explanation_quotes_attributes_<%= explanation_quote.id %>_ref_number" value="<%= explanation_quote.ref_number %>">
  <input type="hidden" name="explanation[explanation_quotes_attributes][<%= explanation_quote.id %>][removed]" id="explanation_explanation_quotes_attributes_<%= explanation_quote.id %>_removed" value="<%= explanation_quote.removed %>">
  <input type="hidden" name="explanation[explanation_quotes_attributes][<%= explanation_quote.id %>][text]" id="explanation_explanation_quotes_attributes_<%= explanation_quote.id %>_text" value="<%= explanation_quote.text %>">
  <blockquote class="quote-text"><%= explanation_quote.text %></blockquote>
  <div class="form-group">
    <input type="url" name="explanation[explanation_quotes_attributes][<%= explanation_quote.id %>][url]" id="explanation_explanation_quotes_attributes_<%= explanation_quote.id %>_url" value="<%= explanation_quote.url %>" class="form-control url-field" placeholder="Quote URL source">
  </div>
</div>

app/views/hypothesis_explanations/_form.html.haml
- is_edit ||= false
- render_preview = @explanation.id.present? && @explanation.body_html.present?
- hypothesis_relation = @hypothesis.relations.where(hypothesis_later_id: @hypothesis.id).first
- relation_initially_toggled = hypothesis_relation.present?

.small-page-header
  %h1
    %span.d-none.d-md-block
      Hypothesis:

- form_submit_path = is_edit ? hypothesis_explanation_path(hypothesis_id: @hypothesis, id: @explanation.id) : hypothesis_explanations_path(hypothesis_id: @hypothesis)
= form_for @explanation, url: form_submit_path, method: (is_edit ? "PATCH" : "POST"), html: {class: "form", id: "explanationForm"} do |f|
  = f.hidden_field :add_to_github, class: "addToGithubField"
  .row
    - if @hypothesis.editable_by?(current_user)
      .max-width-text-container.col
        .form-group
          = label_tag :hypothesis_title do
            Hypothesis text
            %span.small.less-strong
              must be falsifiable
          = text_area_tag :hypothesis_title, @hypothesis.title, class: "form-control"
          - unless relation_initially_toggled
            .less-strong.text-right
              %a.gray-link.small{href: "#hypothesisRelationField", tabindex: -1, "role" => "button", "aria-expanded" => "false", "data-toggle" => "collapse", "data-querykey" => "show_raw", "data-queryvalue" => "true"}
                add hypothesis relationship

      = render partial: "/hypotheses/relation_field", locals: {relation_kind: hypothesis_relation&.kind, related_id: hypothesis_relation&.hypothesis_not(@hypothesis)&.id}

      .max-width-text-container.col
        .form-group.fancy-select.unfancy.create-options-add
          = label_tag :hypothesis_tags_string do
            Topics
            %small.less-strong
              at least 2
          - tags_string = (@hypothesis.tag_titles + tag_titles).uniq # include unapproved tags from this hypothesis in search items
          = select_tag :hypothesis_tags_string, options_for_select(tags_string, @hypothesis.tag_titles), { class: "form-control", required: true, multiple: true}

    - else
      = render partial: "/hypotheses/show_title", locals: {hypothesis: @hypothesis, render_show_link: true}
  .row
    - if @explanation.errors.any?
      .col-md-6.mb-4.mt-2
        = render partial: "/shared/errors", locals: {name: "explanation", obj: @explanation}

  .row.mt-4
    .max-width-text-container.col
      .form-group.mb-0
        = f.label :text do
          %span.explanation-text-label{ title: "Renders with markdown, except no images, links or html" }
            - if is_edit
              Edit new explanation:
            - else
              Create explanation:
        = f.text_area :text, rows: 10, placeholder: "Make your explanation!", class: "form-control"
        .less-strong.text-right
          %a.gray-link{href: "#editingInfo", tabindex: -1, "role" => "button", "aria-expanded" => "false", "data-toggle" => "collapse", "data-querykey" => "show_raw", "data-queryvalue" => "true"}
            editing help
      #editingInfo.collapse
        %ul.mt-2
          %li All explanations need at least one blockquote. Create one by starting a line with ">"
          %li Create italics by putting underscores <em>_around some text_</em>
          %li Make text bold by putting two asterisks <strong>**around text**</strong>
          %li Save to see a preview of what the explanation will look like

  #quoteFieldsWrapper
    #quoteFields.row
      - @explanation.explanation_quotes.not_removed.ref_ordered.each do |explanation_quote|
        = render partial: "/hypothesis_explanations/explanation_quote_fields", locals: {explanation_quote: explanation_quote}

    #quoteFieldsRemoved.removed-quotes.row.collapse{class: (@explanation.explanation_quotes.removed.any? ? "show" : "")}
      .col-12.text-warning
        %h4 Removed quotes
      - @explanation.explanation_quotes.removed.ref_ordered.each do |explanation_quote|
        = render partial: "/hypothesis_explanations/explanation_quote_fields", locals: {explanation_quote: explanation_quote}
  .row.pt-4.mt-5
    .col
      .form-group
        = submit_tag "Save", class: "btn btn-primary"

  - if render_preview
    #explanationPreview.row.explanations-wrapper.mt-4.mb-4.collapse{class: (render_preview ? "show" : "")}
      .max-width-text-container
        .col-12.preview-text.mt-3
          %em.text-info Preview of explanation:
        = render partial: "/hypothesis_explanations/show", locals: {explanation: @explanation, preview: true, skip_edit: true}

  - if is_edit
    .mt-4
      %button#submitForApproval.btn.btn-success.submit-input
        Submit for Approval
        %span.loadingSpinner.spinner-border.spinner-border-sm.collapse.ml-2
          %span.sr-only Loading...
      %em#quoteRequired.collapse.less-strong
        Explanations must include at least one block quote to submit (start line with >)

    %h2.mt-5
      - if @explanation.citations.count == 0
        No existing citations
      - else
        Citations:
    .row#citationsBlock{"data-citeresearchkinds" => Citation.kinds_research.join(",")}
      = f.fields_for :citations do |builder|
        - citation = builder.object
        - explanation_quotes = @explanation.explanation_quotes.where(url: citation.url)
        = render partial: "citation_fields", locals: {f: builder, initially_toggled: ParamsNormalizer.boolean(params[:initially_toggled]), citation: citation, explanation_quotes: explanation_quotes}

.mt-big
= render "/shared/content_license"

app/views/hypothesis_explanations/_show.html.haml
- preview ||= false
- unapproved_show ||= false
- unapproved_show_linked ||= false
- skip_edit ||= false
-# Probably don't want to pass in show_editable?
- show_edit ||= !skip_edit && explanation.editable_by?(current_user)

.col.explanation-show-block.mt-4
  - if unapproved_show || show_edit
    %header.explanation-show-header.d-flex
      - if unapproved_show
        %span.less-strong.small
          %em
            Explanation shown because
            - if unapproved_show_linked
              you clicked a link to view it.
            - else
              you created it.
            It is
            %strong.text-warning not
            approved.
      - if !explanation.approved? && explanation.submitted_to_github?
        %small.ml-auto
          - if explanation.pull_request_number.blank?
            %span.less-strong
              waiting for PR,
              -# Hacky hack, sry
              %a{href: "javascript:void(0);", onclick: "location.reload();"}
                reload
          - else
            = link_to "PR##{explanation.pull_request_number}", explanation.pull_request_url
      - if show_edit
        %small.ml-auto
          = link_to "edit", edit_hypothesis_explanation_path(hypothesis_id: @hypothesis.id, id: explanation.id)

  .explanation-body
    = explanation.body_html&.html_safe

app/views/hypothesis_explanations/edit.html.haml
= render partial: "form", locals: { is_edit: true }

app/views/hypothesis_explanations/new.html.haml
= render partial: "form", locals: { is_edit: false }